{{- if .Values.config.argocd.createSecrets }}
{{- if eq .Values.config.argocd.token.value "" }}
{{- fail "A value for .Values.config.argocd.token.value is required when createSecrets is enabled" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
  labels:
    {{- include "argocd-image-updater.labels" . | nindent 4 }}
type: Opaque
data: 
  argocd.token: {{ .Values.config.argocd.token.value | b64enc }}
{{- end }}
